name: Build Site

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリ取得
        uses: actions/checkout@v4

      - name: Python設定
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ライブラリインストール
        run: pip install requests

      - name: サイト生成
        run: python create_site.py

      - name: FTPアップロード
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/